name: github pages

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - name: Build
        run: npm run build
        env:
          REACT_APP_STARCOIN_API_URL: http://8.131.48.230:8080
          REACT_APP_STARCOIN_NODE_URL: http://39.102.35.25:9850

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: starcoin-explorer/starcoin-explorer.github.io
          publish_branch: master
          publish_dir: ./build
          full_commit_message: ${{ github.event.head_commit.message }}